name: march_yopta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  showcaseview: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/march_1.jpg
    - assets/images/march_2.jpg
    - assets/images/march_3.jpg
    - assets/images/march_4.jpg
    - assets/images/march_5.jpg
    - assets/images/march_6.jpg
    - assets/images/march_7.jpg
    - assets/images/march_8.jpg